# Стадия 1: Сборка
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["PZ3.csproj", "./"]
RUN dotnet restore "PZ3.csproj"

COPY . .
RUN dotnet publish "PZ3.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Стадия 2: Запуск
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "PZ3.dll"]