services:
  pz3-api:
    image: Vorontsovaann/egecourses:latest
    container_name: pz3-container-v18
    ports:
      - "8018:8080"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/config"]
      interval: 30s
      timeout: 5s
      retries: 3