services:
  pz3-api:
    image: Vorontsovaann/egecourses:latest
    container_name: pz3-container-v18
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"  # Берём значения из .env файла
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}  # Берём значение из .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/config"]
      interval: 30s
      timeout: 5s
      retries: 3